include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/docker-dedicated-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy-v2.gitlab-ci.yaml"

stages:
  - build
  - deploy

build:stage:
  only:
    - master
  except:
    - tags
  extends: .build:common

deploy:prod-tycho-testnet:
  only:
    - master
  except:
    - tags
  extends: .deploy
  variables:
    K8S_NAMESPACE: nft-tycho-testnet
    APP_CONFIG: tycho-testnet
  environment:
    name: prod
    on_stop: stop:prod-tycho-testnet
  tags: ["broxus-pve-main"]

stop:prod-tycho-testnet:
  only:
    - master
  except:
    - tags
  extends: .stop
  variables:
    K8S_NAMESPACE: nft-tycho-testnet
    APP_CONFIG: tycho-testnet
  environment:
    name: prod
  tags: ["broxus-pve-main"]


deploy:prod-msha:
  only:
    - master
  except:
    - tags
  extends: .deploy
  variables:
    K8S_NAMESPACE: nft-msha
    APP_CONFIG: msha
  environment:
    name: prod
    on_stop: stop:prod-msha
  tags: ["broxus-pve-main"]

stop:prod-msha:
  only:
    - master
  except:
    - tags
  extends: .stop
  variables:
    K8S_NAMESPACE: nft-msha
    APP_CONFIG: msha
  environment:
    name: prod
  tags: ["broxus-pve-main"]
