---
dist: bionic
language: python
python:
  - "3.6"

services: 
  - docker

env:
  global:
    - ROLE_PATH: $TRAVIS_BUILD_DIR
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

cache:
  directories:
    - /home/travis/.cache/pipenv

install:
  - sudo apt-get install python3.6
  - curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  - sudo -H pip3 install pipenv
  - sudo -H pipenv install

script:
  - sudo -E pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
