---
- name: Converge
  hosts: all
  gather_facts: yes
  remote_user: root

  vars:
    role_path: "{{ lookup('env', 'ROLE_PATH') }}"

  roles:
    - name: "{{ role_path if role_path is defined and role_path else lookup('env', 'HOME') + '/ansible-role-librdkafka' }}"
