---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    output_log: true
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        librdkafka_version: v1.4.2
        librdkafka_checksum: sha256:3b99a36c082a67ef6295eabd4fb3e32ab0bff7c6b0d397d6352697335f4e57eb
        librdkafka_build_opts: --install-deps
verifier:
  name: ansible
