---
- name: Prepare
  hosts: instance
  gather_facts: yes
  become: yes

  tasks:
    - name: Install python dependencies
      apt: 
        name: "{{ item.packages }}"
        update_cache: yes
      when: ansible_distribution_release in item.dist
      loop:
        - dist:
            - buster
            - focal
          packages: 
            - python3-minimal
            - python3-apt
        - dist:
            - stretch
            - bionic
            - xenial
          packages:
            - python-minimal
            - python-apt

    - name: Ensure python is available in PATH
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3
        priority: 1
      when: ansible_distribution_release in ['focal']
