---
- name: Verify
  hosts: all
  gather_facts: no

  tasks: 
    - name: Look for compiled assets
      find:
        path: /usr/local/lib
        pattern: "*rdkafka*"
        file_type: file
        recurse: yes
      register: librdkafka_search

    - name: Ensure search has results
      assert:
        that: librdkafka_search.matched >= 4
