---

- name: Get rustup_user home
  become: yes
  getent:
    database: passwd
    key: "{{ rustup_user }}"
    split: ":"

- name: Define rustup user home
  set_fact:
    rustup_user_home: "{{ getent_passwd[rustup_user][4] }}"

- name: Define rustup user shell
  set_fact:
    rustup_user_shell: "{{ getent_passwd[rustup_user][5] }}"

- name: Create temporary install directory
  tempfile:
    path: "{{ rustup_user_home }}"
    state: directory
    suffix: .install
  register: temp_install_dir
  changed_when: false

- name: Install RustUp
  shell: |
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: "{{ rustup_user_home }}/{{ rustup_cargo_home_suffix }}/bin/rustup"
    executable: /bin/bash
  environment:
    TMPDIR: '{{ temp_install_dir.path }}'
    RUSTUP_HOME: "{{ rustup_user_home }}/{{ rustup_home_suffix }}"
    CARGO_HOME: "{{ rustup_user_home }}/{{ rustup_cargo_home_suffix }}"

- name: Install cargo crates
  shell: |
    set -o pipefail
    cargo install --list | \
    awk 'BEGIN{ code=1 } {if ($1 == "{{ item }}"){ code=0 }} END{ exit code }' || \
    cargo install {{ item }}
  with_items: "{{ rustup_cargo_crates|list }}"
  register: crate_install_result
  changed_when: "'Installed package' in crate_install_result.stderr"
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ rustup_user_home }}/{{ rustup_cargo_home_suffix }}/bin"
    TMPDIR: '{{ temp_install_dir.path }}'
    RUSTUP_HOME: "{{ rustup_user_home }}/{{ rustup_home_suffix }}"
    CARGO_HOME: "{{ rustup_user_home }}/{{ rustup_cargo_home_suffix }}"
  when:
    - rustup_cargo_crates is defined

- name: Install rust runtime config
  template:
    src: "rustrc.j2"
    dest: "{{ rustup_user_home }}/.rustrc"
    owner: "{{ rustup_user }}"
    mode: "0644"
  when:
    - rustup_configure_shell|default(true)

- name: Set shell RC file
  set_fact:
    rustup_shell_rc_settings_file: "{{ item.name }}"
  when:
    - rustup_configure_shell|default(true)
    - rustup_user_shell|regex_replace('^.*/','') == item.shell
    - rustup_shell_rc_settings_file is not defined
  with_items:
    - name: "{{ rustup_user_home }}/.bashrc"
      shell: "bash"
    - name: "{{ rustup_user_home }}/.zshrc"
      shell: "zsh"

- name: Enable rustrc at shell start
  lineinfile: # noqa 208
    dest: "{{ rustup_shell_rc_settings_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: true
    state: present
  with_items:
    - regexp: '^# Setup rustup.*'
      line: '# Setup rustup, cargo path'
    - regexp: 'source.*rustrc$'
      line: "[[ -f {{ rustup_user_home }}/.rustrc ]] && source {{ rustup_user_home }}/.rustrc"
  when:
    - rustup_shell_rc_settings_file is defined
    - rustup_configure_shell|default(true)

- name: Clenaup TemDir
  file:
    path: "{{ temp_install_dir.path }}"
    state: absent
  changed_when: false
