---
- name: Converge
  hosts: all
  tasks:
    - name: Adjust id on manjaro
      lineinfile:
        dest: /etc/os-release
        regexp: 'ID=.*'
        line: 'ID=arch'
        state: present
      when: ansible_os_family == "Archlinux"

    - name: run ansible-rustup role
      include_role:
        name: rustup
