---
galaxy_info:
  author: HurricaneHrndz
  role_name: rustup
  description: Installs rustup and rust toolchain.
  license: MIT
  min_ansible_version: 2.8

  platforms:
   - name: Fedora
     versions:
      - 30
   - name: Ubuntu
     versions:
      - bionic
   - name: Archlinux
     versions:
       - all
   - name: macOS
     versions:
      - all

  galaxy_tags: [rustup, rust, cargo]

dependencies: []
