---
galaxy_info:
  role_name: librdkafka 
  author: Frank Fidanza
  company: RG System
  description: Installs librdkafka from source for Debian/Ubuntu 
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8

  platforms:
    - name: Debian
      versions:
        - buster
        - stretch
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial

  galaxy_tags:
    - librdkafka
    - kafka

dependencies: []
